[package]
name = "audio_processing"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.2"
anyhow = "1.0.75"
bevy = "0.11.3"

[profile.dev]
opt-level = 1


[profile.dev.package."*"]
opt-level = 3